# Generated by Django 4.2.30 on 2026-04-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='marketplaceorder',
            index=models.Index(fields=['user', 'status'], name='marketplace_user_id_f3e784_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplaceorder',
            index=models.Index(fields=['order_number'], name='marketplace_order_n_dbb777_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['vendor', 'status'], name='marketplace_vendor__09775e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='marketplace_categor_e01614_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='marketplace_created_1f132e_idx'),
        ),
    ]
