# Generated by Django 4.2.10 on 2025-04-30 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assistantverification',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Assistant Verification', 'verbose_name_plural': 'Assistant Verifications'},
        ),
        migrations.AddField(
            model_name='assistantverification',
            name='address',
            field=models.TextField(help_text='Current residential address', null=True),
        ),
        migrations.AddField(
            model_name='assistantverification',
            name='phone_number',
            field=models.CharField(help_text='Contact phone number', max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='assistantverification',
            name='full_name',
            field=models.CharField(help_text='Full legal name of the assistant', max_length=255),
        ),
        migrations.AlterField(
            model_name='assistantverification',
            name='id_back',
            field=models.ImageField(help_text='Back side of government-issued ID', upload_to='verification/id_back/'),
        ),
        migrations.AlterField(
            model_name='assistantverification',
            name='id_front',
            field=models.ImageField(help_text='Front side of government-issued ID', upload_to='verification/id_front/'),
        ),
        migrations.AlterField(
            model_name='assistantverification',
            name='id_number',
            field=models.CharField(help_text='Government-issued ID number', max_length=50),
        ),
        migrations.AlterField(
            model_name='assistantverification',
            name='rejected_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if applicable', null=True),
        ),
        migrations.AlterField(
            model_name='assistantverification',
            name='selfie',
            field=models.ImageField(help_text='Selfie of assistant for identity verification', upload_to='verification/selfie/'),
        ),
        migrations.AlterField(
            model_name='assistantverification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', help_text='Current verification status', max_length=20),
        ),
        migrations.AlterField(
            model_name='assistantverification',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the verification was submitted'),
        ),
        migrations.AlterField(
            model_name='assistantverification',
            name='user',
            field=models.OneToOneField(help_text='The user requesting verification', on_delete=django.db.models.deletion.CASCADE, related_name='verification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assistantverification',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When the verification was approved', null=True),
        ),
    ]
