# Generated by Django 4.2.10 on 2025-05-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_assistantverification_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistantverification',
            name='id_back',
        ),
        migrations.RemoveField(
            model_name='assistantverification',
            name='id_front',
        ),
        migrations.RemoveField(
            model_name='assistantverification',
            name='selfie',
        ),
        migrations.AddField(
            model_name='assistantverification',
            name='certificate_image',
            field=models.ImageField(blank=True, help_text='Certificate image for service providers', null=True, upload_to='verification/certificates/'),
        ),
        migrations.AddField(
            model_name='assistantverification',
            name='driving_license_image',
            field=models.ImageField(blank=True, help_text='Image of driving license for riders', null=True, upload_to='verification/driving_license/'),
        ),
        migrations.AddField(
            model_name='assistantverification',
            name='driving_license_number',
            field=models.CharField(blank=True, help_text='Driving license number for riders', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='assistantverification',
            name='less_than_a_year_experience',
            field=models.BooleanField(default=False, help_text='Flag for users with less than a year of experience'),
        ),
        migrations.AddField(
            model_name='assistantverification',
            name='service',
            field=models.CharField(blank=True, help_text='Service provided by service providers', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assistantverification',
            name='user_role',
            field=models.CharField(choices=[('rider', 'Rider'), ('service_provider', 'Service Provider')], help_text='Role of the user: rider or service provider', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='assistantverification',
            name='years_of_experience',
            field=models.CharField(choices=[('less_than_a_year', 'Less than a year'), ('a_year', 'A year'), ('more_than_a_year', '1+ years')], default='less_than_a_year', help_text='Years of experience', max_length=20),
        ),
    ]
