# Generated by Django 4.2.10 on 2025-05-14 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_assistantverification_id_back_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistantverification',
            name='certificate_image',
        ),
        migrations.RemoveField(
            model_name='assistantverification',
            name='driving_license_image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='assistantverification',
            name='area_of_operation',
            field=models.CharField(blank=True, help_text='Area where services will be provided', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assistantverification',
            name='certificate_url',
            field=models.URLField(blank=True, help_text='URL to certificate image in Supabase', null=True),
        ),
        migrations.AddField(
            model_name='assistantverification',
            name='driving_license_url',
            field=models.URLField(blank=True, help_text='URL to driving license image in Supabase', null=True),
        ),
        migrations.AddField(
            model_name='assistantverification',
            name='id_back_url',
            field=models.URLField(blank=True, help_text='URL to ID back image in Supabase', null=True),
        ),
        migrations.AddField(
            model_name='assistantverification',
            name='id_front_url',
            field=models.URLField(blank=True, help_text='URL to ID front image in Supabase', null=True),
        ),
        migrations.AddField(
            model_name='assistantverification',
            name='selfie_url',
            field=models.URLField(blank=True, help_text='URL to selfie image in Supabase', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
