# Generated by Django 4.2.23 on 2025-08-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_wallet_balance_profile_wallet_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(default=False, help_text='Whether the assistant is currently online and available'),
        ),
    ]
