# Generated by Django 5.2.7 on 2025-12-07 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_manager',
            field=models.ForeignKey(blank=True, help_text='Handler assigned as account manager for this client', limit_choices_to={'user_type': 'handler'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_clients', to=settings.AUTH_USER_MODEL),
        ),
    ]
