# Generated by Django 4.2.30 on 2026-04-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_phone_number_alter_user_phone_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='plate_number',
            field=models.CharField(blank=True, help_text='Vehicle plate number for riders', max_length=20, null=True),
        ),
    ]
