# Generated by Django 4.2.10 on 2025-05-21 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_users', models.IntegerField(default=0)),
                ('new_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('total_orders', models.IntegerField(default=0)),
                ('new_orders', models.IntegerField(default=0)),
                ('completed_orders', models.IntegerField(default=0)),
                ('cancelled_orders', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('platform_fee_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ad_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_order_completion_time', models.DurationField(blank=True, null=True)),
                ('avg_response_time', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Metric',
                'verbose_name_plural': 'Daily Metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserRetention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort_date', models.DateField()),
                ('week_1_retention', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('week_2_retention', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('week_4_retention', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('month_1_retention', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('month_2_retention', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('month_3_retention', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('month_6_retention', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cohort_size', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-cohort_date'],
                'unique_together': {('cohort_date',)},
            },
        ),
        migrations.CreateModel(
            name='ServicePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('service_type', models.CharField(choices=[('shopping', 'Shopping'), ('pickup_delivery', 'Pickup & Delivery'), ('cargo_delivery', 'Cargo Delivery'), ('handyman', 'Handyman'), ('banking', 'Banking')], max_length=20)),
                ('total_orders', models.IntegerField(default=0)),
                ('completed_orders', models.IntegerField(default=0)),
                ('cancelled_orders', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('avg_completion_time', models.DurationField(blank=True, null=True)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'service_type'],
                'unique_together': {('date', 'service_type')},
            },
        ),
        migrations.CreateModel(
            name='CustomerSatisfaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('promoters', models.IntegerField(default=0)),
                ('passives', models.IntegerField(default=0)),
                ('detractors', models.IntegerField(default=0)),
                ('nps_score', models.IntegerField(default=0)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
                ('positive_feedback', models.IntegerField(default=0)),
                ('negative_feedback', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='AdvertisementMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ctr', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cpm', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
    ]
