# Generated by Django 4.2.10 on 2025-05-21 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='OrderTracking',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('current_latitude', models.FloatField(blank=True, null=True)),
                        ('current_longitude', models.FloatField(blank=True, null=True)),
                        ('last_updated', models.DateTimeField(auto_now=True)),
                        ('estimated_arrival_time', models.DateTimeField(blank=True, null=True)),
                    ],
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM information_schema.tables
                            WHERE table_schema = 'public'
                              AND table_name = 'orders_ordertracking'
                        ) THEN
                            CREATE TABLE "orders_ordertracking" (
                                "id" bigserial NOT NULL PRIMARY KEY,
                                "current_latitude" double precision NULL,
                                "current_longitude" double precision NULL,
                                "last_updated" timestamp with time zone NOT NULL,
                                "estimated_arrival_time" timestamp with time zone NULL
                            );
                        END IF;
                    END $$;
                    """,
                    reverse_sql='DROP TABLE IF EXISTS "orders_ordertracking" CASCADE;',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='OrderVideo',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('video', models.FileField(upload_to='order_videos/')),
                        ('description', models.CharField(blank=True, max_length=255)),
                        ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                    ],
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM information_schema.tables
                            WHERE table_schema = 'public'
                              AND table_name = 'orders_ordervideo'
                        ) THEN
                            CREATE TABLE "orders_ordervideo" (
                                "id" bigserial NOT NULL PRIMARY KEY,
                                "video" varchar(100) NOT NULL,
                                "description" varchar(255) NULL,
                                "uploaded_at" timestamp with time zone NOT NULL
                            );
                        END IF;
                    END $$;
                    """,
                    reverse_sql='DROP TABLE IF EXISTS "orders_ordervideo" CASCADE;',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='order',
                    name='distance',
                    field=models.FloatField(blank=True, help_text='Distance in kilometers', null=True),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM information_schema.columns
                            WHERE table_schema = 'public'
                              AND table_name = 'orders_order'
                              AND column_name = 'distance'
                        ) THEN
                            ALTER TABLE "orders_order"
                                ADD COLUMN "distance" double precision NULL;
                        END IF;
                    END $$;
                    """,
                    reverse_sql='ALTER TABLE "orders_order" DROP COLUMN IF EXISTS "distance";',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='order',
                    name='estimated_duration',
                    field=models.IntegerField(blank=True, help_text='Estimated duration in minutes', null=True),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM information_schema.columns
                            WHERE table_schema = 'public'
                              AND table_name = 'orders_order'
                              AND column_name = 'estimated_duration'
                        ) THEN
                            ALTER TABLE "orders_order"
                                ADD COLUMN "estimated_duration" integer NULL;
                        END IF;
                    END $$;
                    """,
                    reverse_sql='ALTER TABLE "orders_order" DROP COLUMN IF EXISTS "estimated_duration";',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='ordertype',
                    name='base_price',
                    field=models.DecimalField(decimal_places=2, default=200.0, max_digits=10),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM information_schema.columns
                            WHERE table_schema = 'public'
                              AND table_name = 'orders_ordertype'
                              AND column_name = 'base_price'
                        ) THEN
                            ALTER TABLE "orders_ordertype"
                                ADD COLUMN "base_price" numeric(10,2) NOT NULL DEFAULT 200.00;
                        END IF;
                    END $$;
                    """,
                    reverse_sql='ALTER TABLE "orders_ordertype" DROP COLUMN IF EXISTS "base_price";',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='ordertype',
                    name='min_price',
                    field=models.DecimalField(decimal_places=2, default=200.0, max_digits=10),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM information_schema.columns
                            WHERE table_schema = 'public'
                              AND table_name = 'orders_ordertype'
                              AND column_name = 'min_price'
                        ) THEN
                            ALTER TABLE "orders_ordertype"
                                ADD COLUMN "min_price" numeric(10,2) NOT NULL DEFAULT 200.00;
                        END IF;
                    END $$;
                    """,
                    reverse_sql='ALTER TABLE "orders_ordertype" DROP COLUMN IF EXISTS "min_price";',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='ordertype',
                    name='price_per_km',
                    field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM information_schema.columns
                            WHERE table_schema = 'public'
                              AND table_name = 'orders_ordertype'
                              AND column_name = 'price_per_km'
                        ) THEN
                            ALTER TABLE "orders_ordertype"
                                ADD COLUMN "price_per_km" numeric(10,2) NOT NULL DEFAULT 50.00;
                        END IF;
                    END $$;
                    """,
                    reverse_sql='ALTER TABLE "orders_ordertype" DROP COLUMN IF EXISTS "price_per_km";',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='TrackingWaypoint',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('latitude', models.FloatField()),
                        ('longitude', models.FloatField()),
                        ('waypoint_type', models.CharField(choices=[('pickup', 'Pickup Location'), ('delivery', 'Delivery Location'), ('intermediate', 'Intermediate Stop'), ('custom', 'Custom Waypoint')], default='intermediate', max_length=20)),
                        ('name', models.CharField(blank=True, max_length=255)),
                        ('description', models.TextField(blank=True)),
                        ('arrival_time', models.DateTimeField(blank=True, null=True)),
                        ('departure_time', models.DateTimeField(blank=True, null=True)),
                        ('order_index', models.PositiveSmallIntegerField(default=0)),
                        ('tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='orders.ordertracking')),
                    ],
                    options={
                        'ordering': ['order_index'],
                    },
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM information_schema.tables
                            WHERE table_schema = 'public'
                              AND table_name = 'orders_trackingwaypoint'
                        ) THEN
                            CREATE TABLE "orders_trackingwaypoint" (
                                "id" bigserial NOT NULL PRIMARY KEY,
                                "latitude" double precision NOT NULL,
                                "longitude" double precision NOT NULL,
                                "waypoint_type" varchar(20) NOT NULL,
                                "name" varchar(255) NULL,
                                "description" text NULL,
                                "arrival_time" timestamp with time zone NULL,
                                "departure_time" timestamp with time zone NULL,
                                "order_index" smallint NOT NULL DEFAULT 0,
                                "tracking_id" bigint NOT NULL REFERENCES "orders_ordertracking"("id") DEFERRABLE INITIALLY DEFERRED
                            );
                        END IF;
                    END $$;
                    """,
                    reverse_sql='DROP TABLE IF EXISTS "orders_trackingwaypoint" CASCADE;',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='TrackingLocationHistory',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('latitude', models.FloatField()),
                        ('longitude', models.FloatField()),
                        ('timestamp', models.DateTimeField(auto_now_add=True)),
                        ('tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='orders.ordertracking')),
                    ],
                    options={
                        'ordering': ['-timestamp'],
                    },
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM information_schema.tables
                            WHERE table_schema = 'public'
                              AND table_name = 'orders_trackinglocationhistory'
                        ) THEN
                            CREATE TABLE "orders_trackinglocationhistory" (
                                "id" bigserial NOT NULL PRIMARY KEY,
                                "latitude" double precision NOT NULL,
                                "longitude" double precision NOT NULL,
                                "timestamp" timestamp with time zone NOT NULL,
                                "tracking_id" bigint NOT NULL REFERENCES "orders_ordertracking"("id") DEFERRABLE INITIALLY DEFERRED
                            );
                        END IF;
                    END $$;
                    """,
                    reverse_sql='DROP TABLE IF EXISTS "orders_trackinglocationhistory" CASCADE;',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='TrackingEvent',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('event_type', models.CharField(choices=[('pickup_started', 'Pickup Started'), ('pickup_completed', 'Pickup Completed'), ('delivery_started', 'Delivery Started'), ('delivery_completed', 'Delivery Completed'), ('delay', 'Delay Reported'), ('detour', 'Detour Taken'), ('custom', 'Custom Event')], max_length=20)),
                        ('timestamp', models.DateTimeField(auto_now_add=True)),
                        ('latitude', models.FloatField(blank=True, null=True)),
                        ('longitude', models.FloatField(blank=True, null=True)),
                        ('description', models.TextField(blank=True)),
                        ('tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.ordertracking')),
                    ],
                    options={
                        'ordering': ['-timestamp'],
                    },
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM information_schema.tables
                            WHERE table_schema = 'public'
                              AND table_name = 'orders_trackingevent'
                        ) THEN
                            CREATE TABLE "orders_trackingevent" (
                                "id" bigserial NOT NULL PRIMARY KEY,
                                "event_type" varchar(20) NOT NULL,
                                "timestamp" timestamp with time zone NOT NULL,
                                "latitude" double precision NULL,
                                "longitude" double precision NULL,
                                "description" text NULL,
                                "tracking_id" bigint NOT NULL REFERENCES "orders_ordertracking"("id") DEFERRABLE INITIALLY DEFERRED
                            );
                        END IF;
                    END $$;
                    """,
                    reverse_sql='DROP TABLE IF EXISTS "orders_trackingevent" CASCADE;',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='RiderFeedback',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('clear_communication', models.PositiveSmallIntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')])),
                        ('payment_timeliness', models.PositiveSmallIntegerField(choices=[(1, 'Delayed'), (2, 'On Time')])),
                        ('interaction_quality', models.PositiveSmallIntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')])),
                        ('comments', models.TextField(blank=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rider_feedback', to='orders.order')),
                    ],
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM information_schema.tables
                            WHERE table_schema = 'public'
                              AND table_name = 'orders_riderfeedback'
                        ) THEN
                            CREATE TABLE "orders_riderfeedback" (
                                "id" bigserial NOT NULL PRIMARY KEY,
                                "clear_communication" smallint NOT NULL,
                                "payment_timeliness" smallint NOT NULL,
                                "interaction_quality" smallint NOT NULL,
                                "comments" text NULL,
                                "created_at" timestamp with time zone NOT NULL,
                                "order_id" bigint NOT NULL UNIQUE REFERENCES "orders_order"("id") DEFERRABLE INITIALLY DEFERRED
                            );
                        END IF;
                    END $$;
                    """,
                    reverse_sql='DROP TABLE IF EXISTS "orders_riderfeedback" CASCADE;',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='ReportIssue',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('description', models.TextField()),
                        ('incident_timestamp', models.DateTimeField()),
                        ('reported_at', models.DateTimeField(auto_now_add=True)),
                        ('evidence_photos', models.ManyToManyField(blank=True, to='orders.orderimage')),
                        ('evidence_videos', models.ManyToManyField(blank=True, to='orders.ordervideo')),
                        ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues_reported', to='orders.order')),
                    ],
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM information_schema.tables
                            WHERE table_schema = 'public'
                              AND table_name = 'orders_reportissue'
                        ) THEN
                            CREATE TABLE "orders_reportissue" (
                                "id" bigserial NOT NULL PRIMARY KEY,
                                "description" text NOT NULL,
                                "incident_timestamp" timestamp with time zone NOT NULL,
                                "reported_at" timestamp with time zone NOT NULL,
                                "order_id" bigint NOT NULL REFERENCES "orders_order"("id") DEFERRABLE INITIALLY DEFERRED
                            );
                        END IF;
                    END $$;
                    """,
                    reverse_sql='DROP TABLE IF EXISTS "orders_reportissue" CASCADE;',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Referral',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('redeemed', models.BooleanField(default=False)),
                        ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                        ('referred_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to=settings.AUTH_USER_MODEL)),
                        ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
                    ],
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM information_schema.tables
                            WHERE table_schema = 'public'
                              AND table_name = 'orders_referral'
                        ) THEN
                            CREATE TABLE "orders_referral" (
                                "id" bigserial NOT NULL PRIMARY KEY,
                                "discount_amount" numeric(6,2) NOT NULL DEFAULT 0,
                                "created_at" timestamp with time zone NOT NULL,
                                "redeemed" boolean NOT NULL DEFAULT FALSE,
                                "redeemed_at" timestamp with time zone NULL,
                                "referred_user_id" bigint NOT NULL REFERENCES "accounts_user"("id") DEFERRABLE INITIALLY DEFERRED,
                                "referrer_id" bigint NOT NULL REFERENCES "accounts_user"("id") DEFERRABLE INITIALLY DEFERRED
                            );
                        END IF;
                    END $$;
                    """,
                    reverse_sql='DROP TABLE IF EXISTS "orders_referral" CASCADE;',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Payment',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                        ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('card', 'Card')], max_length=20)),
                        ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                        ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                        ('transaction_reference', models.CharField(max_length=255, unique=True)),
                        ('intasend_checkout_id', models.CharField(blank=True, max_length=255, null=True)),
                        ('intasend_invoice_id', models.CharField(blank=True, max_length=255, null=True)),
                        ('payment_date', models.DateTimeField(auto_now_add=True)),
                        ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                        ('email', models.EmailField(blank=True, max_length=254, null=True)),
                        ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
                    ],
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM information_schema.tables
                            WHERE table_schema = 'public'
                              AND table_name = 'orders_payment'
                        ) THEN
                            CREATE TABLE "orders_payment" (
                                "id" bigserial NOT NULL PRIMARY KEY,
                                "amount" numeric(10,2) NOT NULL,
                                "payment_method" varchar(20) NOT NULL,
                                "status" varchar(20) NOT NULL DEFAULT 'pending',
                                "transaction_id" varchar(255) NULL,
                                "transaction_reference" varchar(255) NOT NULL UNIQUE,
                                "intasend_checkout_id" varchar(255) NULL,
                                "intasend_invoice_id" varchar(255) NULL,
                                "payment_date" timestamp with time zone NOT NULL,
                                "phone_number" varchar(20) NULL,
                                "email" varchar(254) NULL,
                                "order_id" bigint NOT NULL REFERENCES "orders_order"("id") DEFERRABLE INITIALLY DEFERRED
                            );
                        END IF;
                    END $$;
                    """,
                    reverse_sql='DROP TABLE IF EXISTS "orders_payment" CASCADE;',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='ordervideo',
                    name='order',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='orders.order'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM information_schema.columns
                            WHERE table_schema = 'public'
                              AND table_name = 'orders_ordervideo'
                              AND column_name = 'order_id'
                        ) THEN
                            ALTER TABLE "orders_ordervideo"
                                ADD COLUMN "order_id" bigint NOT NULL REFERENCES "orders_order"("id") DEFERRABLE INITIALLY DEFERRED;
                        END IF;
                    END $$;
                    """,
                    reverse_sql='ALTER TABLE "orders_ordervideo" DROP COLUMN IF EXISTS "order_id";',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='ordertracking',
                    name='order',
                    field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='orders.order'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM information_schema.columns
                            WHERE table_schema = 'public'
                              AND table_name = 'orders_ordertracking'
                              AND column_name = 'order_id'
                        ) THEN
                            ALTER TABLE "orders_ordertracking"
                                ADD COLUMN "order_id" bigint NOT NULL UNIQUE REFERENCES "orders_order"("id") DEFERRABLE INITIALLY DEFERRED;
                        END IF;
                    END $$;
                    """,
                    reverse_sql='ALTER TABLE "orders_ordertracking" DROP COLUMN IF EXISTS "order_id";',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='ClientFeedback',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('delivered_promptly', models.PositiveSmallIntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')])),
                        ('professionalism', models.PositiveSmallIntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')])),
                        ('service_quality', models.PositiveSmallIntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')])),
                        ('comments', models.TextField(blank=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_feedback', to='orders.order')),
                    ],
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM information_schema.tables
                            WHERE table_schema = 'public'
                              AND table_name = 'orders_clientfeedback'
                        ) THEN
                            CREATE TABLE "orders_clientfeedback" (
                                "id" bigserial NOT NULL PRIMARY KEY,
                                "delivered_promptly" smallint NOT NULL,
                                "professionalism" smallint NOT NULL,
                                "service_quality" smallint NOT NULL,
                                "comments" text NULL,
                                "created_at" timestamp with time zone NOT NULL,
                                "order_id" bigint NOT NULL UNIQUE REFERENCES "orders_order"("id") DEFERRABLE INITIALLY DEFERRED
                            );
                        END IF;
                    END $$;
                    """,
                    reverse_sql='DROP TABLE IF EXISTS "orders_clientfeedback" CASCADE;',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='CargoValue',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                        ('visible_to_handler_only', models.BooleanField(default=True)),
                        ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_value', to='orders.order')),
                    ],
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM information_schema.tables
                            WHERE table_schema = 'public'
                              AND table_name = 'orders_cargovalue'
                        ) THEN
                            CREATE TABLE "orders_cargovalue" (
                                "id" bigserial NOT NULL PRIMARY KEY,
                                "value" numeric(12,2) NOT NULL,
                                "visible_to_handler_only" boolean NOT NULL DEFAULT TRUE,
                                "order_id" bigint NOT NULL UNIQUE REFERENCES "orders_order"("id") DEFERRABLE INITIALLY DEFERRED
                            );
                        END IF;
                    END $$;
                    """,
                    reverse_sql='DROP TABLE IF EXISTS "orders_cargovalue" CASCADE;',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='CargoPhoto',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('photo', models.ImageField(upload_to='cargo_photos/')),
                        ('description', models.CharField(blank=True, max_length=255)),
                        ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                        ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_photos', to='orders.order')),
                    ],
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM information_schema.tables
                            WHERE table_schema = 'public'
                              AND table_name = 'orders_cargophoto'
                        ) THEN
                            CREATE TABLE "orders_cargophoto" (
                                "id" bigserial NOT NULL PRIMARY KEY,
                                "photo" varchar(100) NOT NULL,
                                "description" varchar(255) NULL,
                                "uploaded_at" timestamp with time zone NOT NULL,
                                "order_id" bigint NOT NULL REFERENCES "orders_order"("id") DEFERRABLE INITIALLY DEFERRED
                            );
                        END IF;
                    END $$;
                    """,
                    reverse_sql='DROP TABLE IF EXISTS "orders_cargophoto" CASCADE;',
                ),
            ],
        ),
    ]
