# Generated by Django 4.2.10 on 2025-05-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_payment_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertype',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordertype',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordertype',
            name='price_per_km',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=10),
        ),
    ]
