# Generated by Django 4.2.10 on 2025-05-23 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_alter_ordertype_base_price_alter_ordertype_min_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankingorder',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banking_orders', to='orders.order'),
        ),
        migrations.AddField(
            model_name='handymanorder',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handyman_orders', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='bankingorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_banking_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='handymanorder',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_handyman_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
