# Generated by Django 4.2.10 on 2025-05-23 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_bankingorder_order_handymanorder_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handymanservicetype',
            name='order_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handyman_service_types', to='orders.ordertype'),
        ),
    ]
