# Generated by Django 4.2.11 on 2025-05-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_handymanservicetype_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='points',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
