# Generated by Django 4.2.11 on 2025-05-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_referral_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price_finalized',
            field=models.BooleanField(default=False),
        ),
    ]
