# Generated by Django 4.2.11 on 2025-05-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_add_price_finalized'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handymanorder',
            name='price',
        ),
        migrations.RemoveField(
            model_name='handymanservicetype',
            name='price_estimate',
        ),
        migrations.AddField(
            model_name='handymanorder',
            name='approved_service_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final approved price for the service', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='handymanorder',
            name='facilitation_fee',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='handymanorder',
            name='facilitation_fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='handymanorder',
            name='final_payment_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='handymanorder',
            name='quote_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='handymanorder',
            name='quote_notes',
            field=models.TextField(blank=True, help_text='Additional notes about the service quote'),
        ),
        migrations.AddField(
            model_name='handymanorder',
            name='quote_provided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='handymanorder',
            name='service_quote',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quote provided by service provider after assessment', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='handymanorder',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total price including facilitation fee and service price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='handymanservicetype',
            name='facilitation_fee',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='handymanorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('quote_provided', 'Quote Provided'), ('quote_approved', 'Quote Approved'), ('quote_rejected', 'Quote Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='handymanservicetype',
            name='name',
            field=models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical Works'), ('landscaping', 'Landscaping')], max_length=100),
        ),
    ]
