# Generated by Django 4.2.23 on 2025-08-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount applied from points', max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount to charge after discounts', max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='points_used',
            field=models.IntegerField(default=0, help_text='Wallet points redeemed (1 point = KSh1)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('payment_pending', 'Payment Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordertype',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=580.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordertype',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=580.0, max_digits=10),
        ),
    ]
