# Generated by Zencoder - make OrderPrepayment.payment_method nullable to support pay_later
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_orderimage_stage_orderattachment_emergencyalert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderprepayment',
            name='payment_method',
            field=models.CharField(
                max_length=20,
                blank=True,
                null=True,
                choices=[('mpesa', 'M-Pesa'), ('card', 'Card')],
            ),
        ),
    ]