# Generated by Django 4.2.23 on 2025-09-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_orderimage_stage_orderattachment_emergencyalert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderprepayment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('mpesa', 'M-Pesa'), ('card', 'Card')], max_length=20, null=True),
        ),
    ]
