# Generated by Django 4.2.23 on 2025-09-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_orderprepayment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='handymanorderimage',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderimage',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quoteimage',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='handymanorderimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='handyman_images/'),
        ),
        migrations.AlterField(
            model_name='orderimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='order_images/'),
        ),
        migrations.AlterField(
            model_name='orderprepayment',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('card', 'Card')], default='mpesa', max_length=20),
        ),
        migrations.AlterField(
            model_name='quoteimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quote_images/'),
        ),
    ]
