# Generated by Django 4.2.23 on 2025-09-06 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_orderprepayment_payment_method_nullable'),
        ('orders', '0017_handymanorderimage_image_url_orderimage_image_url_and_more'),
    ]

    operations = [
    ]
