# Generated by Django 4.2.23 on 2025-09-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_merge_20250906_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handymanorderimage',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='orderimage',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='quoteimage',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='handymanorderimage',
            name='image',
            field=models.ImageField(upload_to='handyman_images/'),
        ),
        migrations.AlterField(
            model_name='orderimage',
            name='image',
            field=models.ImageField(upload_to='order_images/'),
        ),
        migrations.AlterField(
            model_name='quoteimage',
            name='image',
            field=models.ImageField(upload_to='quote_images/'),
        ),
    ]
