# Generated by Django 4.2.23 on 2025-09-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_remove_handymanorderimage_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assistant_items_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final items total from receipt, set by assistant', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderimage',
            name='image_type',
            field=models.CharField(choices=[('generic', 'Generic'), ('receipt', 'Receipt')], default='generic', max_length=20),
        ),
    ]
