# Generated by Django 4.2.23 on 2025-09-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_order_assistant_items_total_orderimage_image_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertype',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=180.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordertype',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=180.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordertype',
            name='price_per_km',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=10),
        ),
    ]
