# Generated by Django 4.2.1 on 2025-10-18 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_remove_banking_transfer_fields'),
        ('orders', '0025_migrate_to_mpesa_daraja'),
    ]

    operations = [
    ]
