# Generated by Django 4.2.1 on 2025-10-19 12:39

from django.db import migrations, models


def remove_fields_if_exist(apps, schema_editor):
    """Safely remove fields if they exist"""
    BankingOrder = apps.get_model('orders', 'BankingOrder')
    db_alias = schema_editor.connection.alias
    
    # Check if table exists and has the fields
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='orders_bankingorder' 
            AND column_name IN ('recipient_account', 'recipient_name')
        """)
        existing_columns = [row[0] for row in cursor.fetchall()]
    
    # Only remove if they exist
    if existing_columns:
        for column in existing_columns:
            if column == 'recipient_account':
                schema_editor.remove_field(BankingOrder, BankingOrder._meta.get_field('recipient_account'))
            elif column == 'recipient_name':
                schema_editor.remove_field(BankingOrder, BankingOrder._meta.get_field('recipient_name'))


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_merge_20251018_1239'),
    ]

    operations = [
        migrations.RunPython(remove_fields_if_exist, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='bankingorder',
            name='transaction_details',
            field=models.TextField(help_text='Cheque details: number, payee name, account to deposit into'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('payment_pending', 'Payment Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client', 'status', '-created_at'], name='idx_cli_stat_cra'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['assistant', 'status', '-created_at'], name='idx_ast_stat_cra'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(condition=models.Q(('status__in', ['pending', 'assigned', 'in_progress', 'payment_pending'])), fields=['client', '-created_at'], name='idx_cli_act_cra'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(condition=models.Q(('status__in', ['pending', 'assigned', 'in_progress', 'payment_pending'])), fields=['assistant', '-created_at'], name='idx_ast_act_cra'),
        ),
    ]
