# Generated by Django 4.2.1 on 2025-10-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_merge_20251018_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankingorder',
            name='recipient_account',
        ),
        migrations.RemoveField(
            model_name='bankingorder',
            name='recipient_name',
        ),
        migrations.AlterField(
            model_name='bankingorder',
            name='transaction_details',
            field=models.TextField(help_text='Cheque details: number, payee name, account to deposit into'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('payment_pending', 'Payment Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client', 'status', '-created_at'], name='idx_cli_stat_cra'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['assistant', 'status', '-created_at'], name='idx_ast_stat_cra'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(condition=models.Q(('status__in', ['pending', 'assigned', 'in_progress', 'payment_pending'])), fields=['client', '-created_at'], name='idx_cli_act_cra'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(condition=models.Q(('status__in', ['pending', 'assigned', 'in_progress', 'payment_pending'])), fields=['assistant', '-created_at'], name='idx_ast_act_cra'),
        ),
    ]
