# Generated by Django 4.2.1 on 2025-10-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_add_mpesa_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='mpesa_transaction_id',
            field=models.CharField(blank=True, help_text='M-Pesa Transaction ID from payment confirmation', max_length=255, null=True),
        ),
    ]
