# Generated by Django 4.2.25 on 2025-11-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_ensure_mpesa_columns_exist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertype',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=250.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordertype',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=250.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordertype',
            name='price_per_km',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=10),
        ),
    ]
