# Generated by Django 5.2.7 on 2025-12-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_alter_ordertype_base_price_alter_ordertype_min_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated value of items (for pickup/delivery orders)', max_digits=12, null=True),
        ),
    ]
