# Generated by Django 4.2.30 on 2026-04-10 10:44

from django.db import migrations, models


def remove_fields_if_exist(apps, schema_editor):
    """Safely remove fields only if they exist"""
    from django.db import connection
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='orders_bankingorder' 
            AND column_name IN ('recipient_account', 'recipient_name')
        """)
        existing_columns = [row[0] for row in cursor.fetchall()]
        
        if 'recipient_account' in existing_columns:
            cursor.execute('ALTER TABLE orders_bankingorder DROP COLUMN recipient_account')
        if 'recipient_name' in existing_columns:
            cursor.execute('ALTER TABLE orders_bankingorder DROP COLUMN recipient_name')


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_revert_order_prices'),
    ]

    operations = [
        migrations.RunPython(remove_fields_if_exist, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='orderprepayment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('ncba', 'NCBA Till'), ('card', 'Card'), ('mpesa', 'M-Pesa (Legacy)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('ncba', 'NCBA Till'), ('card', 'Card'), ('mpesa', 'M-Pesa (Legacy)')], max_length=20),
        ),
    ]
