# Generated by Django 4.2.30 on 2026-04-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_revert_order_prices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankingorder',
            name='recipient_account',
        ),
        migrations.RemoveField(
            model_name='bankingorder',
            name='recipient_name',
        ),
        migrations.AlterField(
            model_name='orderprepayment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('ncba', 'NCBA Till'), ('card', 'Card'), ('mpesa', 'M-Pesa (Legacy)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('ncba', 'NCBA Till'), ('card', 'Card'), ('mpesa', 'M-Pesa (Legacy)')], max_length=20),
        ),
    ]
