# Generated by Django 4.2.30 on 2026-04-13 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_add_draft_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankingorder',
            name='recipient_account',
        ),
        migrations.RemoveField(
            model_name='bankingorder',
            name='recipient_name',
        ),
    ]
