# Generated by Django 4.2.30 on 2026-04-15 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0042_remove_stale_contenttypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('incident_timestamp', models.DateTimeField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('evidence_photos', models.ManyToManyField(blank=True, to='orders.orderimage')),
                ('evidence_videos', models.ManyToManyField(blank=True, to='orders.ordervideo')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues_reported', to='orders.order')),
            ],
        ),
    ]
